version: "3.9"

services:
  api-with-air:
    image: cosmtrek/air
    working_dir: /app
    environment:
      - PANOAPI_URI=http://pano-api-api-with-air-1:8080
    networks:
      - kampus
    ports:
      - "8000:8000"
    volumes:
      - ./.:/app

networks:
  kampus:
    name: kampus